# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: oleksiyrudenko/gha-git-credentials@v2-latest
      with:
        token: '${{ secrets.GITHUB_TOKEN }}'
    - name: download-a-file
      run: |
        echo got to curl part, hope it works
        cd assets/markdownFiles/
        echo changed directory
        curl https://raw.githubusercontent.com/softwareunderground/awesome-open-geoscience/main/README.md -o awesome-open-geoscience_README.md
        echo ran curl
        cd ../
        cd ../
        echo changed back to home directory
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        echo test line
        python -m pip install --upgrade pip
        pip install flake8 pytest markdown
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Get Repos From Files
      run: |
        cd python
        python -m harvest_repos.py
        cd ..
    - name: commit files
      run: |
        git add .
        git commit -m "downloaded new README2.md file"
        echo committed changes and next step is to push via force
    - name: Push changes # push the output folder to your repo
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true
        

