# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application
on: [pull_request, push, issues]
jobs:
  wget:
      runs-on: ubuntu-latest
      steps:
      - name: wget
        uses: wei/wget@v1
        with:
          args: https://raw.githubusercontent.com/softwareunderground/awesome-open-geoscience/main/README.md
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        echo test line
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Download a file
      run: |
        echo got to curl part, hope it works
        curl https://raw.githubusercontent.com/softwareunderground/awesome-open-geoscience/main/README.md -o assets/markdownFiles/awesome-open-geoscience.md
